
import java.awt.Color;
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Frame12 extends javax.swing.JFrame {

    /**
     * Creates new form Frame12
     */
    public Frame12() {
        initComponents();
          setLocation(500,200);
         getContentPane().setBackground(new Color(20,100,220));
          b2.setText("\u2190");
           b15.setText("\u00B1");
           
    }
    void f2(ActionEvent evt){
     String s= l1.getText();
     int a=s.indexOf(".");
      String s1=evt.getActionCommand();
     if(a>0){
         
     }
     else{
         if(s.equals("0")){
          l1.setText("0"+s1);   
         }
         else{
           l1.setText(s+s1);}
       String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
     }
    }
     void f1(ActionEvent evt){
        
            String s= l1.getText();
            String s1=evt.getActionCommand();
       if(s.equals("0")){
       l1.setText(s1);}
     else if(s.equals("-0")){
         l1.setText("-"+s1);
       }
       else{
           l1.setText(s+s1);}
       String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        l1 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox();
        b9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b10 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        b11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        b6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEMPERATURE CONVERTER");
        setResizable(false);

        l1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l1.setText("0");

        b7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b7.setText("CE");
        b7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l2.setText("32");

        b8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b8.setText("8");
        b8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));
        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });

        b9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b9.setText("5");
        b9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("About equal to");

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Temperature  Converter");

        b10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b10.setText("2");
        b10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setText("273.1 K");

        b11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b11.setText("0");
        b11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b12.setText("7");
        b12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b13.setText("4");
        b13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b3.setText("9");
        b3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b14.setText("1");
        b14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b4.setText("6");
        b4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b5.setText("3");
        b5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b6.setText(".");
        b6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(l2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(218, 218, 218))))
        );
        jDesktopPane1.setLayer(l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cb2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(b6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new Frame2().setVisible(true);
        dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
      f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
     l1.setText("0");
        String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
      String s=l1.getText();
      if(s.equals("-0")){
          l1.setText("0");
      }
      else{
      int x=s.length()-1;
       if(x>0){
         String s1=s.substring(0,x);
         l1.setText(s1);}
         else{
             l1.setText("0");
         }}
         String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
      String s=l1.getText();
      l1.setText("-"+s);
      if(s.contains("-")){
      l1.setText(s.substring(1));}
         String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
     f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
       f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
       f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
      f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
      f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        f1(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
      f2(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
         String s2=l1.getText();
       if(cb1.getSelectedItem()=="Celsius"){
         double x=Double.parseDouble(s2);
         double f=(1.8*x)+32;
         double k=x+273.15;
         if(cb2.getSelectedItem()=="Fahrenheit"){
             l2.setText(f+"");
              l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Celsius"){
              l2.setText(s2+"");
              l3.setText(f+"\u00B0"+"F"+" , "+k+"K");}
           if(cb2.getSelectedItem()=="Kelvin"){
               l2.setText(k+"");
               l3.setText(f+"\u00B0"+"F");
           }
         
       }
        if(cb1.getSelectedItem()=="Fahrenheit"){
         double x=Double.parseDouble(s2);
         double c=((x-32)*5)/9;
         double k=((x+459.67)*5)/9;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(k+"K");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(s2+"");
              l3.setText(c+"\u00B0"+"C"+" , "+k+"K");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(k+"");
             l3.setText(c+"\u00B0"+"C");
         }
       }
         if(cb1.getSelectedItem()=="Kelvin"){
         double x=Double.parseDouble(s2);
         double c=x-273.15;
         double f=((x*9)/5)-459.67;
         if(cb2.getSelectedItem()=="Celsius"){
             l2.setText(c+"");
             l3.setText(f+"\u00B0"+"F");
         }
          if(cb2.getSelectedItem()=="Fahrenheit"){
              l2.setText(f+"");
              l3.setText(c+"\u00B0"+"C");}
         if(cb2.getSelectedItem()=="Kelvin"){
             l2.setText(s2+"");
             l3.setText(c+"\u00B0"+"C"+" , "+f+"\u00B0"+"F");
         }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    // End of variables declaration//GEN-END:variables
}
